name: udpocket
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^10.1.2
  http: ^1.1.0
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14
  google_fonts: ^5.1.0
  provider: ^6.0.5
  intl: ^0.18.1
  add_2_calendar: ^2.2.4
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/